project:
  name: quickstart-thousandeyes-amazon-connect
  owner: hashlock@cisco.com
  package_lambda: true
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
  s3_regional_buckets: true
  shorten_stack_name: true

tests:
  default:
    template: ./templates/thousandeyes-connect.template.yaml
    parameters:
      QSS3BucketName:  $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      QSS3KeyPrefix: quickstart-thousandeyes-amazon-connect/ 
      ThousandEyesUserToken: W234dsfgGF53FFDDEghkokfdiu756jn5
      ThousandEyesUser: hashlock@cisco.com
    regions:
    # - af-south-1      # Africa (Cape Town)
    # - ap-east-1       # Asia Pacific (Hong Kong)
    # - ap-northeast-1  # Asia Pacific (Tokyo)
    # - ap-northeast-2  # Asia Pacific (Seoul)
    # - ap-northeast-3  # Asia Pacific (Osaka)
    # - ap-south-1      # Asia Pacific (Mumbai)
    # - ap-southeast-1  # Asia Pacific (Singapore)
    # - ap-southeast-2  # Asia Pacific (Sydney)
    # - ca-central-1    # Canada (Central)
    # - eu-central-1    # Europe (Frankfurt)
    # - eu-north-1      # Europe (Stockholm)
    # - eu-south-1      # Europe (Milan)
    # - eu-west-1       # Europe (Ireland)
    # - eu-west-2       # Europe (London)
    # - eu-west-3       # Europe (Paris)
    # - me-south-1      # Middle East (Bahrain)
    # - sa-east-1       # South America (São Paulo)
      - us-east-1       # US East (N. Virginia)
    # - us-east-2       # US East (Ohio)
    # - us-west-1       # US West (N. California)
    # - us-west-2       # US West (Oregon)