//Include any predeployment steps here, such as signing up for a Marketplace AMI or making any changes to a partner account. If there are no predeployment steps, leave this file empty.

== Predeployment steps

=== Setting Up ThousandEyes

The following steps assume you have a ThousandEyes account. If you do not, you can sign-up for a https://www.thousandeyes.com/signup/[14-day free trial at here].

=== Deploy and Configure ThousandEyes Endpoint Agents
First you'll want to setup your ThousandEyes monitoring by deploying ThosuandEyes Endpoint Agents. ThousandEyes Endpoint Agents monitor network and app performance across the internet as well as collect device health. With Endpoint Agents installed on your Amazon Connect users' devices, you'll be able to quickly identify any network or device issues that may be impacting a user's experience of Amazon Connect.

Follow the steps in this https://docs.thousandeyes.com/product-documentation/global-vantage-points/endpoint-agents/quick-guide-on-endpoint-agent#configuring-and-deploying-the-endpoint-agent[Endpoint deployment guide] o install the ThousandEyes Endpoint agent on any Windows or MacOS based user device.

Note - for each deployed agent, note the Agent Name. You will use this when setting up the client widget below. The agent name is typically the device host name. For example: `+hans-mac-us`+

=== Configure ThousandEyes to Monitor Amazon Connect
Once you've deployed at least one ThousandEyes Endpoint Agent you'll want to configure ThousandEyes to monitor Amazon Connect from those agents.

=== Create a Scheduled Test
First you'll need to create a "Scheduled Test".

. Log in to your ThousandEyes account at https://app.thousandeyes.com
. Select Endpoint Agent --> https://app.thousandeyes.com/endpoint/test-settings/[Test Settings]
. Select "Add New Test" and create a new "Web - HTTP Server" test
. In the URL field enter the URL of your Amazon Connect service. For example `+https://acmebusiness.my.connect.aws]`+.
. Name the test AmazonConnect or something similar. You will use this name when setting up the client widget (see below)